### ISSUE TITLE
Mini project 1 idea

### ISSUE THREAD

**Issue by taha59** [trogers19/MiniProject1-445#1]
For q1, I plan to compare Outpost and Standish of Standish: a story of the pilgrims by Jane G. Austin.
https://www.gutenberg.org/cache/epub/4676/pg4676.txt
https://www.gutenberg.org/cache/epub/22052/pg22052.txt

For q2, I plan to compare the works of Jane G. Austin to the works of Gerald Cumberland.
Works of Gerald Cumberland: 
https://www.gutenberg.org/files/61437/61437-0.txt
https://www.gutenberg.org/files/60272/60272-0.txt

For q3 I can compare the highest frequency of one to the lesser frequency of another.

**Comment by trogers19** [comment]
Hi! I think those plans sound good. Is there a reason you picked those texts or authors in particular? I imagine it will at least be convenient to use the Gutenberg site. Good luck with your analysis!
